### ISSUE TITLE
Грешка в примера

### ISSUE THREAD

**Issue by confestim** [miglen/egn#1]
В примера пише: `egn.validate(123123123)`,
докато `egn.validate()` приема str() аргументи. 
Например: `egn.validate("12242432423")`

**Comment by miglen** [comment]
Така е, недовършен е модула. Ако искаш прати PR или ще ги погледна уикенда.

**Comment by miglen** [comment]
Сега го прегледах, приема и двете и ако е integer ще го обърне в string.
```
    if isinstance(egn, int):
        egn = str('{0:0=10d}'.format(egn))
```
