### ISSUE TITLE
Тази празна функция

### ISSUE THREAD

**Issue by confestim** [miglen/egn#2]
![image](https://user-images.githubusercontent.com/36108495/95736325-be264300-0c8e-11eb-82aa-a2b5fd5933b5.png)
Тази празна функция обезмисля това да пишете, че могат да се генерират егн-та с вашето library.

**Comment by miglen** [comment]
Привет, поправих го в последния комит [9ad1799](https://github.com/miglen/egn/commit/9ad17992429db98b454de73d1a3540225257cd70) ще се радвам да го тестваш и ако не работи нещо отвори този тикет.
